# Generated by Django 4.0.5 on 2022-07-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('change_type', models.CharField(max_length=255)),
                ('change_comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('external_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255, null=True)),
                ('course_role', models.CharField(max_length=255, null=True)),
                ('availability_status', models.CharField(max_length=255, null=True)),
                ('datasource_id', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dsktool.messages')),
            ],
        ),
    ]
